[package]
name = "vulkan_bloom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.36.0"
ash-window = "0.9.1"
gpu-alloc = "0.5.3"
gpu-alloc-ash = "0.4.0"
winit = "0.25.0"
ultraviolet = "0.8.1"
memoffset = "0.6.5"
obj-rs = "0.7.0"
imgui = "0.8.2"
imgui-winit-support = "0.8.2"
imgui-rs-vulkan-renderer = "1.2"